project:
  type: website
  output-dir: docs

website:
  title: "Moisés Santillán"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: curriculum.qmd
        text: CV
      - href: publications.qmd
        text: Publications
      - href: courses.qmd
        text: Courses
  margin-header: | 
      ![](/media/cinvestav.png){width=75}

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


